'use client';
import { sampleConsents, sampleRightsRequests, sampleBreaches, dpdpChecklist, dashboardMetrics, categoryLabels, purposeLabels } from '@/lib/data';
import { BarChart3, Download, TrendingUp, Shield, Users, AlertTriangle, CheckCircle, Calendar } from 'lucide-react';

export default function ReportsPage() {
  const m = dashboardMetrics;

  const consentByPurpose = Object.entries(purposeLabels).map(([key, label]) => ({
    purpose: label,
    count: sampleConsents.filter(c => c.purposes.includes(key as never)).length,
  })).filter(x => x.count > 0);

  const requestsByType = [
    { type: 'Data Access', count: sampleRightsRequests.filter(r => r.requestType === 'access').length },
    { type: 'Correction', count: sampleRightsRequests.filter(r => r.requestType === 'correction').length },
    { type: 'Erasure', count: sampleRightsRequests.filter(r => r.requestType === 'erasure').length },
    { type: 'Grievance', count: sampleRightsRequests.filter(r => r.requestType === 'grievance').length },
    { type: 'Withdrawal', count: sampleRightsRequests.filter(r => r.requestType === 'withdrawal').length },
  ].filter(x => x.count > 0);

  const maxConsent = Math.max(...consentByPurpose.map(x => x.count));
  const maxRequest = Math.max(...requestsByType.map(x => x.count));

  function generateReport() {
    const compliantCount = dpdpChecklist.filter(i => i.status === 'compliant').length;
    const partialCount = dpdpChecklist.filter(i => i.status === 'partial').length;
    const nonCompliantCount = dpdpChecklist.filter(i => i.status === 'non_compliant').length;
    const notAssessedCount = dpdpChecklist.filter(i => i.status === 'not_assessed').length;

    const report = `DPDP ACT 2023 COMPLIANCE REPORT
Generated: ${new Date().toLocaleDateString('en-IN')}
Organisation: Your Company Pvt. Ltd.
Reporting Period: January 2026 – March 2026

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

EXECUTIVE SUMMARY
━━━━━━━━━━━━━━━━
Overall Compliance Score: ${m.complianceScore}%
Total Requirements Assessed: ${dpdpChecklist.length}
  • Compliant: ${compliantCount}
  • Partial Compliance: ${partialCount}
  • Non-Compliant: ${nonCompliantCount}
  • Not Assessed: ${notAssessedCount}

CONSENT MANAGEMENT
━━━━━━━━━━━━━━━━━
Total Consent Records: ${m.totalConsents}
Active Consents: ${m.activeConsents}
Withdrawn Consents: ${m.withdrawnConsents}
Expired Consents: ${sampleConsents.filter(c => c.status === 'expired').length}

DATA PRINCIPAL RIGHTS
━━━━━━━━━━━━━━━━━━━━
Total Requests: ${sampleRightsRequests.length}
Pending: ${sampleRightsRequests.filter(r => r.status === 'pending').length}
In Review: ${sampleRightsRequests.filter(r => r.status === 'in_review').length}
Completed: ${sampleRightsRequests.filter(r => r.status === 'completed').length}
Overdue: ${m.overdueRequests}

DATA BREACH INCIDENTS
━━━━━━━━━━━━━━━━━━━━
Total Breaches: ${sampleBreaches.length}
Open Breaches: ${m.openBreaches}
Critical Breaches: ${m.criticalBreaches}
DPB Notifications Sent: ${sampleBreaches.filter(b => b.notifiedDPB).length}
Total Records Affected: ${sampleBreaches.reduce((acc, b) => acc + b.affectedRecords, 0).toLocaleString()}

DATA INVENTORY
━━━━━━━━━━━━━
Total Data Assets: ${m.dataAssets}
Sensitive Data Assets: ${2}
Children's Data Assets: ${1}
Cross-border Transfers: ${1}

NON-COMPLIANT AREAS (ACTION REQUIRED)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${dpdpChecklist.filter(i => i.status === 'non_compliant').map(i => `• ${i.requirement} (${i.reference})`).join('\n')}

PARTIAL COMPLIANCE (IMPROVEMENTS NEEDED)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${dpdpChecklist.filter(i => i.status === 'partial').map(i => `• ${i.requirement} — ${i.notes || 'Review needed'}`).join('\n')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Report generated by DPDP Comply Tool
Digital Personal Data Protection Act, 2023`;

    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `dpdp-compliance-report-${new Date().toISOString().split('T')[0]}.txt`;
    a.click();
  }

  return (
    <div>
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-2xl font-bold text-slate-800">Reports &amp; Analytics</h1>
          <p className="text-slate-500 text-sm mt-1">DPDP compliance reporting and insights</p>
        </div>
        <button onClick={generateReport}
          className="flex items-center gap-2 px-4 py-2 bg-indigo-600 text-white rounded-lg text-sm hover:bg-indigo-700">
          <Download className="w-4 h-4" /> Download Full Report
        </button>
      </div>

      {/* Overview KPIs */}
      <div className="grid grid-cols-4 gap-4 mb-6">
        {[
          { label: 'Compliance Score', value: `${m.complianceScore}%`, icon: TrendingUp, bg: 'bg-indigo-50', ic: 'text-indigo-600', sub: 'DPDP Act 2023' },
          { label: 'Active Consents', value: m.activeConsents, icon: Shield, bg: 'bg-green-50', ic: 'text-green-600', sub: `of ${m.totalConsents} total` },
          { label: 'Open Requests', value: m.pendingRightsRequests, icon: Users, bg: 'bg-amber-50', ic: 'text-amber-600', sub: `${m.overdueRequests} overdue` },
          { label: 'Active Breaches', value: m.openBreaches, icon: AlertTriangle, bg: 'bg-red-50', ic: 'text-red-600', sub: `${m.criticalBreaches} critical` },
        ].map(({ label, value, icon: Icon, bg, ic, sub }) => (
          <div key={label} className="bg-white rounded-xl border border-slate-200 p-5">
            <div className="flex items-start justify-between">
              <div>
                <div className="text-sm text-slate-500">{label}</div>
                <div className="text-3xl font-bold text-slate-800 mt-1">{value}</div>
                <div className="text-xs text-slate-400 mt-1">{sub}</div>
              </div>
              <div className={`w-10 h-10 rounded-lg ${bg} flex items-center justify-center`}>
                <Icon className={`w-5 h-5 ${ic}`} />
              </div>
            </div>
          </div>
        ))}
      </div>

      <div className="grid grid-cols-2 gap-6 mb-6">
        {/* Compliance by Section */}
        <div className="bg-white rounded-xl border border-slate-200 p-5">
          <h2 className="font-semibold text-slate-800 mb-4">Compliance by DPDP Section</h2>
          {[...new Set(dpdpChecklist.map(i => i.section))].map(section => {
            const items = dpdpChecklist.filter(i => i.section === section);
            const score = Math.round((items.reduce((acc, i) => {
              if (i.status === 'compliant') return acc + 1;
              if (i.status === 'partial') return acc + 0.5;
              return acc;
            }, 0) / items.length) * 100);
            const compliant = items.filter(i => i.status === 'compliant').length;
            const partial = items.filter(i => i.status === 'partial').length;
            const nonCompliant = items.filter(i => i.status === 'non_compliant').length;
            return (
              <div key={section} className="mb-4">
                <div className="flex justify-between items-center mb-1">
                  <span className="text-sm text-slate-600">{section}</span>
                  <div className="flex items-center gap-2">
                    <span className="text-xs text-slate-400">{compliant}✓ {partial}◑ {nonCompliant}✗</span>
                    <span className={`text-sm font-semibold ${score >= 80 ? 'text-green-600' : score >= 50 ? 'text-amber-600' : 'text-red-600'}`}>{score}%</span>
                  </div>
                </div>
                <div className="h-2.5 bg-slate-100 rounded-full overflow-hidden">
                  <div className={`h-full rounded-full ${score >= 80 ? 'bg-green-500' : score >= 50 ? 'bg-amber-500' : 'bg-red-500'}`} style={{ width: `${score}%` }} />
                </div>
              </div>
            );
          })}
        </div>

        {/* Consent by Purpose */}
        <div className="bg-white rounded-xl border border-slate-200 p-5">
          <h2 className="font-semibold text-slate-800 mb-4">Consents by Purpose</h2>
          <div className="space-y-3">
            {consentByPurpose.map(({ purpose, count }) => (
              <div key={purpose}>
                <div className="flex justify-between text-sm mb-1">
                  <span className="text-slate-600">{purpose}</span>
                  <span className="font-semibold text-indigo-600">{count}</span>
                </div>
                <div className="h-2.5 bg-slate-100 rounded-full overflow-hidden">
                  <div className="h-full bg-indigo-500 rounded-full" style={{ width: `${(count / maxConsent) * 100}%` }} />
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>

      <div className="grid grid-cols-2 gap-6 mb-6">
        {/* Rights Requests Breakdown */}
        <div className="bg-white rounded-xl border border-slate-200 p-5">
          <h2 className="font-semibold text-slate-800 mb-4">Rights Requests by Type</h2>
          <div className="space-y-3">
            {requestsByType.map(({ type, count }) => (
              <div key={type}>
                <div className="flex justify-between text-sm mb-1">
                  <span className="text-slate-600">{type}</span>
                  <span className="font-semibold text-blue-600">{count}</span>
                </div>
                <div className="h-2.5 bg-slate-100 rounded-full overflow-hidden">
                  <div className="h-full bg-blue-500 rounded-full" style={{ width: `${(count / maxRequest) * 100}%` }} />
                </div>
              </div>
            ))}
          </div>
          <div className="mt-4 pt-4 border-t border-slate-100">
            <div className="grid grid-cols-3 gap-2">
              {[
                { label: 'Avg Resolution', value: '8 days', color: 'text-green-600' },
                { label: 'SLA Compliance', value: '80%', color: 'text-blue-600' },
                { label: 'Overdue', value: `${m.overdueRequests}`, color: 'text-red-600' },
              ].map(({ label, value, color }) => (
                <div key={label} className="text-center p-2 bg-slate-50 rounded-lg">
                  <div className={`text-lg font-bold ${color}`}>{value}</div>
                  <div className="text-xs text-slate-500">{label}</div>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Breach Summary */}
        <div className="bg-white rounded-xl border border-slate-200 p-5">
          <h2 className="font-semibold text-slate-800 mb-4">Data Breach Summary</h2>
          <div className="space-y-3 mb-4">
            {[
              { label: 'Total Breaches', value: sampleBreaches.length, color: 'bg-slate-100 text-slate-700' },
              { label: 'Critical Severity', value: sampleBreaches.filter(b => b.severity === 'critical').length, color: 'bg-red-100 text-red-700' },
              { label: 'High Severity', value: sampleBreaches.filter(b => b.severity === 'high').length, color: 'bg-orange-100 text-orange-700' },
              { label: 'DPB Notified', value: sampleBreaches.filter(b => b.notifiedDPB).length, color: 'bg-green-100 text-green-700' },
              { label: 'Total Records Affected', value: sampleBreaches.reduce((a, b) => a + b.affectedRecords, 0).toLocaleString(), color: 'bg-blue-100 text-blue-700' },
            ].map(({ label, value, color }) => (
              <div key={label} className={`flex justify-between items-center px-3 py-2 rounded-lg ${color}`}>
                <span className="text-sm">{label}</span>
                <span className="font-bold">{value}</span>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Upcoming Actions */}
      <div className="bg-white rounded-xl border border-slate-200 p-5">
        <div className="flex items-center gap-2 mb-4">
          <Calendar className="w-4 h-4 text-indigo-500" />
          <h2 className="font-semibold text-slate-800">Upcoming Compliance Deadlines</h2>
        </div>
        <div className="space-y-3">
          {dpdpChecklist.filter(i => i.dueDate).sort((a, b) => (a.dueDate || '').localeCompare(b.dueDate || '')).map(item => (
            <div key={item.id} className="flex items-center justify-between p-3 bg-slate-50 rounded-lg">
              <div>
                <div className="text-sm font-medium text-slate-800">{item.requirement}</div>
                <div className="text-xs text-slate-500">{item.section} • {item.reference}</div>
                {item.notes && <div className="text-xs text-amber-600 mt-0.5">{item.notes}</div>}
              </div>
              <div className="text-right flex-shrink-0 ml-4">
                <div className="text-sm font-semibold text-slate-700">{item.dueDate}</div>
                <div className="text-xs text-slate-400">{item.assignedTo}</div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Non-compliant items */}
      <div className="mt-6 bg-red-50 border border-red-200 rounded-xl p-5">
        <div className="flex items-center gap-2 mb-3">
          <AlertTriangle className="w-4 h-4 text-red-600" />
          <h2 className="font-semibold text-red-800">Non-Compliant Areas — Immediate Action Required</h2>
        </div>
        <div className="space-y-2">
          {dpdpChecklist.filter(i => i.status === 'non_compliant').map(item => (
            <div key={item.id} className="flex items-start gap-3 p-3 bg-white rounded-lg border border-red-200">
              <div className="w-2 h-2 rounded-full bg-red-500 mt-1.5 flex-shrink-0" />
              <div>
                <div className="text-sm font-semibold text-slate-800">{item.requirement}</div>
                <div className="text-xs text-slate-500">{item.description}</div>
                <div className="text-xs text-red-600 mt-1 font-medium">{item.reference}</div>
                {item.notes && <div className="text-xs text-slate-600 mt-1 italic">{item.notes}</div>}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
